name: youtube-dl-service
on: [push, workflow_dispatch]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: youtube-dl-service deploy
      env:
        YOUTUBE_DL_SERVICE_TOKEN: ${{ secrets.YOUTUBE_DL_SERVICE_TOKEN }}
        ENDPOINT: "vstavrinov/youtube-dl-service/actions/workflows/main.yml"
      run: |
        COMMIT=$(git rev-parse --short $GITHUB_SHA)
        curl -s -X POST                                         \
            -H "Accept: application/vnd.github.v3+json"         \
            -H "Authorization: token $YOUTUBE_DL_SERVICE_TOKEN" \
            -d '{"ref": "master"
                 "inputs":
                   {"youtube-dl": "$COMMIT"}
              }'                                                 \
        https://api.github.com/repos/$ENDPOINT/dispatches
