name: youtube-dl-service
on: [push, workflow_dispatch]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: youtube-dl-service deploy
      env:
        YOUTUBE_DL_SERVICE_TOKEN: ${{ secrets.YOUTUBE_DL_SERVICE_TOKEN }}
        ENDPOINT: "vstavrinov/youtube-dl-service/actions/workflows/main.yml"
      run: ./youtube-dl-service.sh
